import os
L = chr(123)
R = chr(125)
B = chr(92)
Q = chr(34)
NL = chr(10)

lines = []
def a(s):
    lines.append(s)

a("// DXGI Desktop Duplication Capture Backend for AtlasRemote")
a("// Falls back to GDI if DXGI is unavailable.")
a("")
a("use std::time::" + L + "Instant, Duration" + R + ";")
a("")
a("use atlas_frame::" + L + "Frame, PixelFormat, FrameSource" + R + ";")
a("use anyhow::" + L + "Result, Context" + R + ";")
a("")
a("use windows::core::Interface;")
a("use windows::Win32::Foundation::HWND;")
a("use windows::Win32::Graphics::Dxgi::*;")
a("use windows::Win32::Graphics::Direct3D11::*;")
a("use windows::Win32::Graphics::Direct3D::*;")
a("use windows::Win32::Graphics::Gdi::*;")
a("use windows::Win32::UI::WindowsAndMessaging::*;")
a("")
a("pub struct DxgiCapture " + L)
a("    name: String,")
a("    width: u32,")
a("    height: u32,")
a("    fallback_gdi: bool,")
a("    duplication: Option<IDXGIOutputDuplication>,")
a("    device: Option<ID3D11Device>,")
a("    context: Option<ID3D11DeviceContext>,")
a("    staging_tex: Option<ID3D11Texture2D>,")
a("    last_acquire: Option<Instant>,")
a("    frame_counter: u64,")
a(R + ";")
a("")
a("impl DxgiCapture " + L)
a("    pub fn new(monitor_index: u32) -> Result<Self> " + L)
a("        eprintln!(" + Q + "[CAPTURE] Trying DXGI Desktop Duplication (monitor " + B + "u)" + Q + ", monitor_index);")
a("        match Self::new_dxgi(monitor_index) " + L)
a("            Ok(cap) => " + L)
a("                eprintln!(" + Q + "[CAPTURE] DXGI OK: " + B + "u" + Q + ", cap.name);")
a("                Ok(cap)")
a("            " + R + " Err(e) => " + L)
a("                eprintln!(" + Q + "[CAPTURE] DXGI fail: " + B + "u, fallback GDI" + Q + ", e);")
a("                Self::new_gdi()")
a("            " + R)
a("        " + R)
a("    " + R)
a("")
a("    fn new_dxgi(monitor_index: u32) -> Result<Self> " + L)
a("        let factory = unsafe " + L + " CreateDXGIFactory2(0).context(" + Q + "Failed to create DXGI factory" + Q + ")?" + R + ";")
a("        let mut adapter: Option<IDXGIAdapter1> = None;")
a("        let mut output_idx: u32 = 0;")
a("        let mut target_out_idx: u32 = 0;")
a("        let mut found = false;")
a("        for ad_idx in 0u32.. " + L)
a("            let ad = match unsafe " + L + " factory.EnumAdapters1(ad_idx) " + R + " " + L)
a("                Ok(a) => a,")
a("                Err(_) => break,")
a("            " + R + ";")
a("            for out_i in 0u32.. " + L)
a("                if unsafe " + L + " ad.EnumOutputs(out_i) " + R + " .is_ok() " + L)
a("                    if output_idx == monitor_index " + L)
a("                        adapter = Some(ad);")
a("                        target_out_idx = out_i;")
a("                        found = true;")
a("                        break;")
a("                    " + R)
a("                    output_idx += 1;")
a("                " + R)
a("            " + R)
a("        " + R)
a("        if !found " + L + " return Err(anyhow::anyhow!(" + Q + "Monitor index " + B + "u not found" + Q + ", monitor_index));" + R)
a("        let adapter = adapter.unwrap();")
a("        let mut desc_buf = [0u16; 128];")
a("        unsafe " + L)
a("            let ad_desc = adapter.GetDesc1().context(" + Q + "GetDesc1 failed" + Q + ")?;")
a("            let p = ad_desc.Description.as_ptr();")
a("            for i in 0..128 " + L + " desc_buf[i] = *p.add(i); if desc_buf[i] == 0 " + L + " break" + R + " " + R + ";")
a("        " + R + ";")
a("        let name = String::from_utf16_lossy(&desc_buf[..desc_buf.iter().position(|&c| c == 0).unwrap_or(128)]);")
a("        let (device, context) = unsafe " + L)
a("            D3D11CreateDevice(")
a("                Some(&adapter),")
a("                D3D_DRIVER_TYPE_UNKNOWN,")
a("                None,")
a("                D3D11_CREATE_DEVICE_BGRA_SUPPORT,")
a("                &[],")
a("                D3D11_SDK_VERSION,")
a("                None,")
a("                None,")
a("            ).context(" + Q + "D3D11CreateDevice failed" + Q + ")?")
a("        " + R + ";")
a("        let device = device.context(" + Q + "D3D11 device is null" + Q + ")?;")
a("        let context = context.context(" + Q + "D3D11 context is null" + Q + ")?;")
a("        let output = unsafe " + L + " adapter.EnumOutputs(target_out_idx).context(" + Q + "EnumOutputs failed" + Q + ")?" + R + ";")
a("        let duplication = unsafe " + L + " output.DuplicateOutput(&device).context(" + Q + "DuplicateOutput failed" + Q + ")?" + R + ";")
a("        let width = unsafe " + L + " GetSystemMetrics(SM_CXSCREEN) " + R + " as u32;")
a("        let height = unsafe " + L + " GetSystemMetrics(SM_CYSCREEN) " + R + " as u32;")
a("        let desc = D3D11_TEXTURE2D_DESC " + L)
a("            Width: width, Height: height,")
a("            MipLevels: 1, ArraySize: 1,")
a("            Format: DXGI_FORMAT_B8G8R8A8_UNORM,")
a("            SampleDesc: D3D11_SAMPLE_DESC " + L + " Count: 1, Quality: 0 " + R + ",")
a("            Usage: D3D11_USAGE_STAGING,")
a("            BindFlags: 0,")
a("            CPUAccessFlags: D3D11_CPU_ACCESS_READ,")
a("            MiscFlags: 0,")
a("        " + R + ";")
a("        let staging_tex = unsafe " + L)
a("            device.CreateTexture2D(&desc, None).context(" + Q + "CreateTexture2D failed" + Q + ")?")
a("        " + R + ";")
a("        Ok(DxgiCapture " + L)
a("            name, width, height, fallback_gdi: false,")
a("            duplication: Some(duplication),")
a("            device: Some(device),")
a("            context: Some(context),")
a("            staging_tex: Some(staging_tex),")
a("            last_acquire: None,")
a("            frame_counter: 0,")
a("        " + R + ")")
a("    " + R)
a("")
a("    fn new_gdi() -> Result<Self> " + L)
a("        let width = unsafe " + L + " GetSystemMetrics(SM_CXSCREEN) " + R + " as u32;")
a("        let height = unsafe " + L + " GetSystemMetrics(SM_CYSCREEN) " + R + " as u32;")
a("        eprintln!(" + Q + "[CAPTURE] GDI fallback: " + B + "ux" + B + "u" + Q + ", width, height);")
a("        Ok(DxgiCapture " + L)
a("            name: format!(" + Q + "GDI " + B + "ux" + B + "u" + Q + ", width, height),")
a("            width, height, fallback_gdi: true,")
a("            duplication: None, device: None, context: None,")
a("            staging_tex: None, last_acquire: None, frame_counter: 0,")
a("        " + R + ")")
a("    " + R)
a("}")

path = r"D:\Android\AtlasRemote\crates\capture\src\dxgi.rs"
with open(path, "w", encoding="utf-8", newline="\r\n") as f:
    f.write("\n".join(lines) + "\n")
print(f"Part1 written: {len(lines)} lines")
