
L = chr(123)
R = chr(125)
B = chr(92)
Q = chr(34)
NL = chr(10)

lines = []
def a(s=''):
    lines.append(s)

a()
a('impl DxgiCapture ' + L)
a('    fn next_frame_dxgi(&mut self) -> Result<Option<Frame>> ' + L)
a('        let duplication = self.duplication.as_ref().context(' + Q + 'No duplication object' + Q + ')?;')
a('        let device = self.device.as_ref().context(' + Q + 'No device' + Q + ')?;')
a('        let context = self.context.as_ref().context(' + Q + 'No context' + Q + ')?;')
a('        let staging_tex = self.staging_tex.as_ref().context(' + Q + 'No staging tex' + Q + ')?;')
a()
a('        let rate_limit_ms = 33u64;')
a('        let now = Instant::now();')
a('        if let Some(last) = self.last_acquire ' + L + ' if now.duration_since(last).as_millis() < rate_limit_ms ' + L + ' return Ok(None);' + R + ' ' + R)
a()
a('        let mut retrieved = false;')
a('        let mut resource: Option<ID3D11Resource> = None;')
a('        let mut screen_data: DXGI_MAPPED_RECT = unsafe ' + L + ' std::mem::zeroed()' + R + ';')
a()
a('        loop ' + L)
a('            match unsafe ' + L + ' duplication.AcquireNextFrame(100, std::ptr::null_mut(), &mut resource)' + R + ' ' + L)
a('                Ok(_) => ' + L + ' retrieved = true; break; ' + R)
a('                Err(e) if e.code() == windows::core::HRESULT(0x887A0006) => ' + L)
a('                    std::thread::sleep(Duration::from_millis(1));')
a('                    continue;')
a('                ' + R)
a('                Err(e) => ' + L)
a('                    eprintln!(' + Q + '[DXGI] AcquireNextFrame error: ' + B + 'u' + Q + ', e);')
a('                    return Ok(None);')
a('                ' + R)
a('            ' + R)
a('        ' + R)
a()
a('        if !retrieved ' + L + ' return Ok(None);' + R)
a('        let resource = resource.context(' + Q + 'Acquired resource is null' + Q + ')?;')
a()
a('        unsafe ' + L + ' context.CopyResource(staging_tex, &resource);' + R)
a()
a('        let map_res = unsafe ' + L + ' context.Map(staging_tex, 0, D3D11_MAP_READ, 0)' + R + ';')
a('        let mapped = match map_res ' + L)
a('            Ok(m) => m,')
a('            Err(e) => ' + L)
a('                eprintln!(' + Q + '[DXGI] Map failed: ' + B + 'u' + Q + ', e);')
a('                unsafe ' + L + ' duplication.ReleaseFrame();' + R)
a('                return Ok(None);')
a('            ' + R)
a('        ' + R)
a('        screen_data = mapped;')
a('        let _unmap_guard = DropGuard(| | unsafe ' + L + ' context.Unmap(staging_tex, 0);' + R + ');')
a()
a('        let width = self.width.max(1);')
a('        let height = self.height.max(1);')
a('        let row_pitch = screen_data.Pitch as usize;')
a('        let stride = 4;')
a('        let mut data = Vec::with_capacity((width * height * stride) as usize);')
a()
a('        let src_ptr = screen_data.pBits as *const u8;')
a('        for y in 0..height ' + L)
a('            let src_row = unsafe ' + L + ' src_ptr.add(row_pitch * y as usize)' + R + ';')
a('            for x in 0..width ' + L)
a('                let src_pixel = unsafe ' + L + ' src_row.add(x as usize * stride)' + R + ';')
a('                let b = *src_pixel;')
a('                let g = *src_pixel.add(1);')
a('                let r = *src_pixel.add(2);')
a('                let a = *src_pixel.add(3);')
a('                data.push(r);')
a('                data.push(g);')
a('                data.push(b);')
a('                data.push(a);')
a('            ' + R)
a('        ' + R)
a()
a('        self.frame_counter += 1;')
a('        if self.frame_counter % 30 == 0 ' + L + ' unsafe ' + L + ' duplication.ReleaseFrame();' + R + ' ' + R)
a('        self.last_acquire = Some(Instant::now());')
a()
a('        let ts = std::time::SystemTime::now()')
a('            .duration_since(std::time::UNIX_EPOCH)')
a('            .map(|d| d.as_millis() as u64)')
a('            .unwrap_or(0);')
a()
a('        Ok(Some(Frame ' + L)
a('            timestamp: ts,')
a('            width,')
a('            height,')
a('            format: PixelFormat::Rgba32,')
a('            data,')
a('            frame_id: self.frame_counter,')
a('        ' + R + '))')
a('    ' + R)
a()
a('    fn next_frame_gdi(&mut self) -> Result<Option<Frame>> ' + L)
a('        let (width, height) = if self.width > 0 && self.height > 0 ' + L + ' (self.width, self.height)' + R + ' else ' + L)
a('            let w = unsafe ' + L + ' GetSystemMetrics(SM_CXSCREEN)' + R + ' as u32;')
a('            let h = unsafe ' + L + ' GetSystemMetrics(SM_CYSCREEN)' + R + ' as u32;')
a('            (w, h)')
a('        ' + R)
a('        let buf_size = (width * height * 4) as usize;')
a()
a('        let hdc = unsafe ' + L + ' GetDC(HWND(0))' + R + ';')
a('        if hdc.0 == 0 ' + L + ' return Ok(None);' + R)
a('        let hdc_mem = unsafe ' + L + ' CreateCompatibleDC(hdc)' + R + ';')
a('        if hdc_mem.0 == 0 ' + L + ' unsafe ' + L + ' ReleaseDC(HWND(0), hdc);' + R + ' return Ok(None);' + R)
a()
a('        let bm_info = BITMAPINFO ' + L)
a('            bmiHeader: BITMAPINFOHEADER ' + L)
a('                biSize: std::mem::size_of::<BITMAPINFOHEADER>() as u32,')
a('                biWidth: width as i32,')
a('                biHeight: -(height as i32),')
a('                biPlanes: 1,')
a('                biBitCount: 32,')
a('                biCompression: BI_RGB,')
a('                biSizeImage: 0,')
a('                biXPelsPerMeter: 0,')
a('                biYPelsPerMeter: 0,')
a('                biClrUsed: 0,')
a('                biClrImportant: 0,')
a('            ' + R + ',')
a('        ' + R + ';')
a()
a('        let hbmp = unsafe ' + L + ' CreateDIBSection(hdc_mem, &bm_info, DIB_RGB_COLORS, std::ptr::null_mut(), None, 0)' + R + ';')
a('        if hbmp.0 == 0 ' + L + ' unsafe ' + L + ' DeleteDC(hdc_mem); unsafe ' + L + ' ReleaseDC(HWND(0), hdc);' + R + ' return Ok(None);' + R)
a()
a('        let h_old = unsafe ' + L + ' SelectObject(hdc_mem, hbmp)' + R + ';')
a('        let captured = unsafe ' + L + ' BitBlt(hdc_mem, 0, 0, width as i32, height as i32, hdc, 0, 0, SRCCOPY | CAPTUREBLT)' + R + ';')
a('        if !captured.as_bool() ' + L + ' unsafe ' + L + ' SelectObject(hdc_mem, h_old); DeleteObject(hbmp); DeleteDC(hdc_mem); ReleaseDC(HWND(0), hdc);' + R + ' return Ok(None);' + R)
a()
a('        let mut bits = vec![0u8; buf_size];')
a('        unsafe ' + L)
a('            let info = BITMAPINFO ' + L)
a('                bmiHeader: BITMAPINFOHEADER ' + L)
a('                    biSize: std::mem::size_of::<BITMAPINFOHEADER>() as u32,')
a('                    biWidth: width as i32,')
a('                    biHeight: -(height as i32),')
a('                    biPlanes: 1,')
a('                    biBitCount: 32,')
a('                    biCompression: BI_RGB,')
a('                    biSizeImage: buf_size as u32,')
a('                    biXPelsPerMeter: 0,')
a('                    biYPelsPerMeter: 0,')
a('                    biClrUsed: 0,')
a('                    biClrImportant: 0,')
a('                ' + R + ',')
a('            ' + R + ';')
a('            GetDIBits(hdc_mem, hbmp, 0, height, bits.as_mut_ptr() as *mut _, &info as *const _, DIB_RGB_COLORS);')
a('        ' + R)
a()
a('        let mut rgba = Vec::with_capacity(buf_size);')
a('        for i in (0..buf_size).step_by(4) ' + L)
a('            let b = bits[i];')
a('            let g = bits[i + 1];')
a('            let r = bits[i + 2];')
a('            let a = bits[i + 3];')
a('            rgba.extend_from_slice(&[r, g, b, a]);')
a('        ' + R)
a()
a('        unsafe ' + L + ' SelectObject(hdc_mem, h_old); DeleteObject(hbmp); DeleteDC(hdc_mem); ReleaseDC(HWND(0), hdc);' + R)
a()
a('        let ts = std::time::SystemTime::now()')
a('            .duration_since(std::time::UNIX_EPOCH)')
a('            .map(|d| d.as_millis() as u64)')
a('            .unwrap_or(0);')
a('        Ok(Some(Frame ' + L + ' timestamp: ts, width, height, format: PixelFormat::Rgba32, data: rgba, frame_id: 0, ' + R + '))')
a('    ' + R)
a('}')
a()
a('impl FrameSource for DxgiCapture ' + L)
a('    fn next_frame(&mut self) -> Option<Frame> ' + L)
a('        if self.fallback_gdi ' + L)
a('            match self.next_frame_gdi() ' + L)
a('                Ok(f) => f,')
a('                Err(e) => ' + L + ' eprintln!(' + Q + '[GDI] Capture error: ' + B + 'u' + Q + ', e); None' + R)
a('            ' + R)
a('        ' + R + ' else ' + L)
a('            match self.next_frame_dxgi() ' + L)
a('                Ok(f) => f,')
a('                Err(e) => ' + L)
a('                    eprintln!(' + Q + '[DXGI] Capture error: ' + B + 'u, falling back to GDI' + Q + ', e);')
a('                    self.fallback_gdi = true;')
a('                    match self.next_frame_gdi() ' + L)
a('                        Ok(f) => f,')
a('                        Err(e2) => ' + L + ' eprintln!(' + Q + '[GDI] Also failed: ' + B + 'u' + Q + ', e2); None' + R)
a('                    ' + R)
a('                ' + R)
a('            ' + R)
a('        ' + R)
a('    ' + R)
a()
a('    fn name(&self) -> &str ' + L + ' &self.name' + R)
a('}' + R)
a()
a('pub type ScreenCapture = DxgiCapture;')
a()
a('struct DropGuard<F: FnMut()>(F);')
a('impl<F: FnMut()> Drop for DropGuard<F> ' + L + ' fn drop(&mut self) ' + L + ' self.0();' + R + ' ' + R + R)

path = r'D:\Android\AtlasRemote\crates\capture\_dxgi_new.rs'
with open(path, 'a', encoding='utf-8', newline='\r\n') as f:
    f.write('\n'.join(lines) + '\n')
print(f'Part2 OK: {len(lines)} lines')
